#!/bin/bash

go get fyne.io/fyne/v2@$1
go mod tidy
echo DONE
pwd

cd gui
go get fyne.io/fyne/v2@$1
go mod tidy
echo DONE
pwd
cd ..

cd theme2
go get fyne.io/fyne/v2@$1
go mod tidy
echo DONE
pwd
cd ..
