#!/bin/bash

go get github.com/stuartdd/jsonParserGo/parser@$1
go mod tidy
echo DONE
pwd

cd gui
go get github.com/stuartdd/jsonParserGo/parser@$1
go mod tidy
echo DONE
pwd
cd ..

cd lib
go get github.com/stuartdd/jsonParserGo/parser@$1
go mod tidy
echo DONE
pwd
cd ..

cd pref
go get github.com/stuartdd/jsonParserGo/parser@$1
go mod tidy
echo DONE
pwd
cd ..
